In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [2]:
NO_SAMPLES = 5000
NO_FEATURES = 100

In [3]:
def create_random_data() -> None:
    global x_train, y_train
    x_train = np.random.rand(NO_SAMPLES, NO_FEATURES).astype(dtype=np.float16)
    y_train = (np.random.randn(NO_SAMPLES, 1) < 0).astype(dtype=np.int32)
    return

In [5]:
# create_random_data()

In [6]:
X = tf.Variable(initial_value=x_train, dtype=tf.float16, name="X")
X.shape

2025-03-25 21:25:37.602801: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2 Pro
2025-03-25 21:25:37.603009: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 32.00 GB
2025-03-25 21:25:37.603022: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 10.67 GB
2025-03-25 21:25:37.603355: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-03-25 21:25:37.603371: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


TensorShape([5000, 100])

In [11]:
# import sys
#
# sys.getsizeof(X)
# gpus = tf.config.list_physical_devices('GPU')
# gpus

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [18]:
initializer = tf.keras.initializers.GlorotNormal()
W = tf.Variable(initializer(shape=(X.shape[1], 512), dtype=tf.float16), trainable=True)
b = tf.Variable(tf.zeros(shape=(512,), dtype=tf.float16), trainable=True)
with tf.GradientTape() as tape:
    Z = tf.add(tf.matmul(X, W), b)
    A = tf.nn.sigmoid(Z)
    pass
grads = tape.gradient(target=A, sources=[W, b])
grads

[<tf.Tensor: shape=(100, 512), dtype=float16, numpy=
 array([[589.5, 613.5, 613.5, ..., 607. , 610.5, 609.5],
        [602. , 624.5, 624. , ..., 617. , 621. , 620. ],
        [598. , 621.5, 621.5, ..., 615. , 619. , 618. ],
        ...,
        [599.5, 624. , 624. , ..., 618. , 622. , 621. ],
        [596. , 619.5, 618. , ..., 612. , 615.5, 616. ],
        [605.5, 629. , 627.5, ..., 622. , 626. , 625. ]], dtype=float16)>,
 <tf.Tensor: shape=(512,), dtype=float16, numpy=
 array([1194., 1241., 1239., 1154., 1218., 1231., 1244., 1236., 1231.,
        1215., 1222., 1228., 1198., 1237., 1238., 1242., 1238., 1200.,
        1234., 1235., 1128., 1238., 1236., 1227., 1153., 1115., 1233.,
        1178., 1042., 1232., 1204., 1241., 1242., 1212., 1241., 1237.,
        1236., 1224., 1137., 1217., 1241., 1241., 1232., 1241., 1241.,
        1227., 1232.,  883., 1159., 1196., 1231., 1236., 1206., 1232.,
        1200., 1171., 1234., 1161., 1241., 1234., 1241., 1232., 1237.,
        1152., 1114., 1220.,

In [22]:
# create input data
X = tf.random.normal((4, 3), dtype=tf.float32)  # batch_size=4, input_dim=3

# init layer 1
W1 = tf.Variable(tf.random.normal((3, 5)), trainable=True)  # input_dim=3, hidden_dim=5
b1 = tf.Variable(tf.zeros((5,)), trainable=True)

# init layer 2
W2 = tf.Variable(tf.random.normal((5, 2)), trainable=True)  # hidden_dim=5, output_dim=2
b2 = tf.Variable(tf.zeros((2,)), trainable=True)

# Forward pass
with tf.GradientTape(persistent=True) as tape:
    # layer 1
    Z1 = tf.matmul(X, W1) + b1  # Shape: (4, 5)
    # layer 2
    Z2 = tf.matmul(Z1, W2) + b2  # Shape: (4, 2)
    # loss
    loss = tf.reduce_sum(Z2)  # Z2 reduce to scalar

dL_dZ1 = tape.gradient(loss, Z1)  # Shape: (4, 5)
grads_Z1 = tape.gradient(Z1, [W1, b1], output_gradients=dL_dZ1)

grads_Z1_1 = tape.gradient(loss, [W1, b1])

print("Shape of Z1:", Z1.shape)
print("Shape of dL/dZ1 (output_gradients):", dL_dZ1.shape)
print("Gradient of W1:", grads_Z1[0].shape)
print("Gradient of b1:", grads_Z1[1].shape)
print("\nGradient of W1 (sample):", grads_Z1[0].numpy())
print("Gradient of b1 (sample):", grads_Z1[1].numpy())
print("\nGradient of W1 loss:", grads_Z1_1[0].numpy())
print("Gradient of W1 loss:", grads_Z1_1[1].numpy())

grads_loss = tape.gradient(loss, [W1, b1])
print("\nGradient of W1 loss:", grads_loss[0].shape)
print("Gradient of b1 loss:", grads_loss[1].shape)

del tape

Shape of Z1: (4, 5)
Shape of dL/dZ1 (output_gradients): (4, 5)
Gradient of W1: (3, 5)
Gradient of b1: (5,)

Gradient of W1 (sample): [[-1.757903   -1.6067742  -2.539984    0.44706905 -1.0642006 ]
 [ 1.2829103   1.172617    1.8536698  -0.3262691   0.7766491 ]
 [ 0.8370626   0.76509947  1.2094669  -0.21288133  0.5067416 ]]
Gradient of b1 (sample): [-4.0940866 -3.7421136 -5.9155226  1.0412061 -2.4784813]

Gradient of W1 loss: [[-1.757903   -1.6067742  -2.539984    0.44706905 -1.0642006 ]
 [ 1.2829103   1.172617    1.8536698  -0.3262691   0.7766491 ]
 [ 0.8370626   0.76509947  1.2094669  -0.21288133  0.5067416 ]]
Gradient of W1 loss: [-4.0940866 -3.7421136 -5.9155226  1.0412061 -2.4784813]

Gradient of W1 loss: (3, 5)
Gradient of b1 loss: (5,)


In [24]:
import tensorflow as tf

X = tf.random.normal((4, 3), dtype=tf.float32)  # batch_size=4, input_dim=3
y_true = tf.random.normal((4, 2), dtype=tf.float32)  # output_dim=2

W1 = tf.Variable(tf.random.normal((3, 5)), trainable=True)  # input_dim=3, hidden_dim1=5
b1 = tf.Variable(tf.zeros((5,)), trainable=True)

W2 = tf.Variable(tf.random.normal((5, 4)), trainable=True)  # hidden_dim1=5, hidden_dim2=4
b2 = tf.Variable(tf.zeros((4,)), trainable=True)

W3 = tf.Variable(tf.random.normal((4, 2)), trainable=True)  # hidden_dim2=4, output_dim=2
b3 = tf.Variable(tf.zeros((2,)), trainable=True)

# Forward pass
with tf.GradientTape(persistent=True) as tape:
    # layer 1
    Z1 = tf.matmul(X, W1) + b1  # Shape: (4, 5)
    A1 = tf.nn.relu(Z1)
    # layer 2
    Z2 = tf.matmul(A1, W2) + b2  # Shape: (4, 4)
    A2 = tf.nn.relu(Z2)
    # layer 3
    Z3 = tf.matmul(A2, W3) + b3  # Shape: (4, 2)
    # MSE loss
    loss = tf.reduce_mean(tf.square(Z3 - y_true))

# Calculate gradient loss respect to Z1 (output_gradients)
dL_dZ1 = tape.gradient(loss, Z1)  # Shape: (4, 5)

# Calculate gradient Z1 respect to W1 and b1, dL_dZ1 as output_gradients
grads_Z1 = tape.gradient(Z1, [W1, b1], output_gradients=dL_dZ1)

# Calculate gradient loss directly
grads_loss = tape.gradient(loss, [W1, b1])

print("Shape of Z1:", Z1.shape)
print("Shape if dL/dZ1 (output_gradients):", dL_dZ1.shape)
print("Gradient of W1 respect to Z1:", grads_Z1[0].shape)
print("Gradient of b1 respect Z1:", grads_Z1[1].shape)
print("\nGradient of W1 from loss:", grads_loss[0].shape)
print("Gradient of b1 from loss:", grads_loss[1].shape)

print("\nGradient of W1 respect to Z1 (sample):", grads_Z1[0].numpy())
print("Gradient of b1 respect to Z1 (sample):", grads_Z1[1].numpy())

print("\nGradient of W1 respect to Z1 ():", grads_loss[0].numpy())
print("Gradient of b1 respect to Z1 ():", grads_loss[1].numpy())

del tape

Shape of Z1: (4, 5)
Shape if dL/dZ1 (output_gradients): (4, 5)
Gradient of W1 respect to Z1: (3, 5)
Gradient of b1 respect Z1: (5,)

Gradient of W1 from loss: (3, 5)
Gradient of b1 from loss: (5,)

Gradient of W1 respect to Z1 (sample): [[-3.8292165  -1.0301048   0.          0.         -1.81614   ]
 [ 1.4133823   1.4539416   0.          0.          4.2164764 ]
 [-2.8116374   0.03549701  0.          0.          2.036872  ]]
Gradient of b1 respect to Z1 (sample): [3.8456235 1.6883235 0.        0.        3.772709 ]

Gradient of W1 respect to Z1 (): [[-3.8292165  -1.0301048   0.          0.         -1.81614   ]
 [ 1.4133823   1.4539416   0.          0.          4.2164764 ]
 [-2.8116374   0.03549701  0.          0.          2.036872  ]]
Gradient of b1 respect to Z1 (): [3.8456235 1.6883235 0.        0.        3.772709 ]


In [2]:
import tensorflow as tf

# input data
X = tf.random.normal((4, 3), dtype=tf.float32)  # batch_size=4, input_dim=3
y_true = tf.random.normal((4, 2), dtype=tf.float32)  # output_dim=2
m = X.shape[0]

# init layer 1
W1 = tf.Variable(tf.random.normal((3, 5)), trainable=True)  # input_dim=3, hidden_dim1=5
b1 = tf.Variable(tf.zeros((5,)), trainable=True)

# init layer 2
W2 = tf.Variable(tf.random.normal((5, 4)), trainable=True)  # hidden_dim1=5, hidden_dim2=4
b2 = tf.Variable(tf.zeros((4,)), trainable=True)

# init layer 3
W3 = tf.Variable(tf.random.normal((4, 2)), trainable=True)  # hidden_dim2=4, output_dim=2
b3 = tf.Variable(tf.zeros((2,)), trainable=True)

# L2 regularization
l2_lambda = 0.01

# Optimizer
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

# Forward pass and loss
with tf.GradientTape(persistent=True) as tape:
    # layer 1
    Z1 = tf.matmul(X, W1) + b1  # Shape: (4, 5)
    A1 = tf.nn.relu(Z1)
    # layer 2
    Z2 = tf.matmul(A1, W2) + b2  # Shape: (4, 4)
    A2 = tf.nn.relu(Z2)
    # layer 3
    Z3 = tf.matmul(A2, W3) + b3  # Shape: (4, 2)
    # MSE
    mse_loss = tf.reduce_mean(tf.square(Z3 - y_true))
    # L2 regularization
    l2_loss = (l2_lambda / (2 * m)) * (tf.reduce_sum(tf.square(W1)) +
                           tf.reduce_sum(tf.square(W2)) +
                           tf.reduce_sum(tf.square(W3)))
    # loss
    loss = mse_loss + l2_loss

# Loss gradient respect to Z1 (output_gradients)
dL_dZ1 = tape.gradient(loss, Z1)  # Shape: (4, 5)

# Z1 gradient respect to W1 and b1, dL_dZ1 as output_gradients
grads_Z1 = tape.gradient(Z1, [W1, b1], output_gradients=dL_dZ1)

# gradient before update
print("Trước khi cập nhật:")
print("Gradient of W1 respect to Z1:", grads_Z1[0].shape)
print("Gradient of b1 respect to Z1:", grads_Z1[1].shape)
print("W1 (sample):", W1.numpy()[:1])  # In một phần của W1
print("b1 (sample):", b1.numpy())

# update W1 and b1 with optimizer
optimizer.apply_gradients(zip(grads_Z1, [W1, b1]))

# after update
print("\nafter update:")
print("W1 (sample):", W1.numpy()[:1])
print("b1 (sample):", b1.numpy())

# Calculate gradient directly from loss for comparison
grads_loss = tape.gradient(loss, [W1, b1])
print("\nGradient of W1 from loss:", grads_loss)

Trước khi cập nhật:
Gradient of W1 respect to Z1: (3, 5)
Gradient of b1 respect to Z1: (5,)
W1 (sample): [[ 0.22524154  0.16996656  0.23449701  0.19718769 -0.2524347 ]]
b1 (sample): [0. 0. 0. 0. 0.]

after update:
W1 (sample): [[ 0.22524154  0.17996646  0.22449711  0.19718769 -0.2624346 ]]
b1 (sample): [ 0.          0.00999991 -0.00999991  0.         -0.00999991]

Gradient of W1 from loss: [<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[ 5.6310382e-04, -1.1275313e+00,  1.2115437e+00,  4.9296924e-04,
         1.1424298e+00],
       [ 4.6409899e-03,  1.3486383e+00, -1.4519565e+00,  2.5297445e-03,
        -1.2512712e+00],
       [-1.2788365e-03, -6.9765943e-01,  7.4312741e-01, -1.7442016e-04,
         6.0380077e-01]], dtype=float32)>, <tf.Tensor: shape=(5,), dtype=float32, numpy=
array([ 0.       , -1.5626848,  1.6776757,  0.       ,  1.4808562],
      dtype=float32)>]
