In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [2]:
NO_SAMPLES = 5000
NO_FEATURES = 100

In [3]:
def create_random_data() -> None:
    global x_train, y_train
    x_train = np.random.rand(NO_SAMPLES, NO_FEATURES).astype(dtype=np.float16)
    y_train = (np.random.randn(NO_SAMPLES, 1) < 0).astype(dtype=np.int32)
    return

In [4]:
create_random_data()

In [5]:
X = tf.Variable(initial_value=x_train, dtype=tf.float16, name="X")
X.shape

2025-04-10 22:29:32.235458: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2 Pro
2025-04-10 22:29:32.235493: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 32.00 GB
2025-04-10 22:29:32.235498: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 10.67 GB
2025-04-10 22:29:32.235542: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-04-10 22:29:32.235578: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


TensorShape([5000, 100])

In [6]:
# import sys
#
# sys.getsizeof(X)
# gpus = tf.config.list_physical_devices('GPU')
# gpus

In [7]:
initializer = tf.keras.initializers.GlorotNormal()
W = tf.Variable(initializer(shape=(X.shape[1], 512), dtype=tf.float16), trainable=True)
b = tf.Variable(tf.zeros(shape=(512,), dtype=tf.float16), trainable=True)
with tf.GradientTape() as tape:
    Z = tf.add(tf.matmul(X, W), b)
    A = tf.nn.sigmoid(Z)
    pass
grads = tape.gradient(target=A, sources=[W, b])
grads

[<tf.Tensor: shape=(100, 512), dtype=float16, numpy=
 array([[570. , 617. , 609. , ..., 618. , 593.5, 600.5],
        [573.5, 618.5, 611. , ..., 619.5, 594.5, 602. ],
        [576.5, 623. , 615.5, ..., 623.5, 600. , 604. ],
        ...,
        [583.5, 630. , 622. , ..., 630.5, 606. , 612.5],
        [570.5, 616. , 608. , ..., 616.5, 594. , 596.5],
        [571. , 618.5, 612. , ..., 620. , 595. , 603.5]], dtype=float16)>,
 <tf.Tensor: shape=(512,), dtype=float16, numpy=
 array([1146., 1238., 1223., 1143., 1100., 1202., 1233., 1221., 1241.,
        1243., 1149., 1138., 1197., 1173., 1242., 1226., 1215., 1241.,
        1139., 1220., 1233., 1228., 1240., 1199., 1238., 1222., 1180.,
        1240., 1241., 1148., 1192., 1239., 1229., 1212., 1208., 1239.,
        1240., 1191., 1239., 1219., 1243., 1237., 1229., 1219., 1205.,
        1156., 1178., 1242., 1213., 1232., 1226., 1169., 1242., 1230.,
        1211., 1235., 1203., 1213., 1226., 1239., 1216., 1227., 1234.,
        1170., 1238., 1183.,

In [8]:
# create input data
X = tf.random.normal((4, 3), dtype=tf.float32)  # batch_size=4, input_dim=3

# init layer 1
W1 = tf.Variable(tf.random.normal((3, 5)), trainable=True)  # input_dim=3, hidden_dim=5
b1 = tf.Variable(tf.zeros((5,)), trainable=True)

# init layer 2
W2 = tf.Variable(tf.random.normal((5, 2)), trainable=True)  # hidden_dim=5, output_dim=2
b2 = tf.Variable(tf.zeros((2,)), trainable=True)

# Forward pass
with tf.GradientTape(persistent=True) as tape:
    # layer 1
    Z1 = tf.matmul(X, W1) + b1  # Shape: (4, 5)
    # layer 2
    Z2 = tf.matmul(Z1, W2) + b2  # Shape: (4, 2)
    # loss
    loss = tf.reduce_sum(Z2)  # Z2 reduce to scalar

dL_dZ1 = tape.gradient(loss, Z1)  # Shape: (4, 5)
grads_Z1 = tape.gradient(Z1, [W1, b1], output_gradients=dL_dZ1)

grads_Z1_1 = tape.gradient(loss, [W1, b1])

print("Shape of Z1:", Z1.shape)
print("Shape of dL/dZ1 (output_gradients):", dL_dZ1.shape)
print("Gradient of W1:", grads_Z1[0].shape)
print("Gradient of b1:", grads_Z1[1].shape)
print("\nGradient of W1 (sample):", grads_Z1[0].numpy())
print("Gradient of b1 (sample):", grads_Z1[1].numpy())
print("\nGradient of W1 loss:", grads_Z1_1[0].numpy())
print("Gradient of W1 loss:", grads_Z1_1[1].numpy())

grads_loss = tape.gradient(loss, [W1, b1])
print("\nGradient of W1 loss:", grads_loss[0].shape)
print("Gradient of b1 loss:", grads_loss[1].shape)

del tape

Shape of Z1: (4, 5)
Shape of dL/dZ1 (output_gradients): (4, 5)
Gradient of W1: (3, 5)
Gradient of b1: (5,)

Gradient of W1 (sample): [[ -4.5524354    9.937477     4.021035    -1.4367888  -11.658628  ]
 [  0.35801154  -0.7815008   -0.31622133   0.11299162   0.9168552 ]
 [ -2.8193173    6.154267     2.4902217   -0.88980144  -7.2201734 ]]
Gradient of b1 (sample): [ 4.2582808 -9.29537   -3.7612169  1.343951  10.905309 ]

Gradient of W1 loss: [[ -4.5524354    9.937477     4.021035    -1.4367888  -11.658628  ]
 [  0.35801154  -0.7815008   -0.31622133   0.11299162   0.9168552 ]
 [ -2.8193173    6.154267     2.4902217   -0.88980144  -7.2201734 ]]
Gradient of W1 loss: [ 4.2582808 -9.29537   -3.7612169  1.343951  10.905309 ]

Gradient of W1 loss: (3, 5)
Gradient of b1 loss: (5,)


In [9]:
import tensorflow as tf

X = tf.random.normal((4, 3), dtype=tf.float32)  # batch_size=4, input_dim=3
y_true = tf.random.normal((4, 2), dtype=tf.float32)  # output_dim=2

W1 = tf.Variable(tf.random.normal((3, 5)), trainable=True)  # input_dim=3, hidden_dim1=5
b1 = tf.Variable(tf.zeros((5,)), trainable=True)

W2 = tf.Variable(tf.random.normal((5, 4)), trainable=True)  # hidden_dim1=5, hidden_dim2=4
b2 = tf.Variable(tf.zeros((4,)), trainable=True)

W3 = tf.Variable(tf.random.normal((4, 2)), trainable=True)  # hidden_dim2=4, output_dim=2
b3 = tf.Variable(tf.zeros((2,)), trainable=True)

# Forward pass
with tf.GradientTape(persistent=True) as tape:
    # layer 1
    Z1 = tf.matmul(X, W1) + b1  # Shape: (4, 5)
    A1 = tf.nn.relu(Z1)
    # layer 2
    Z2 = tf.matmul(A1, W2) + b2  # Shape: (4, 4)
    A2 = tf.nn.relu(Z2)
    # layer 3
    Z3 = tf.matmul(A2, W3) + b3  # Shape: (4, 2)
    # MSE loss
    loss = tf.reduce_mean(tf.square(Z3 - y_true))

# Calculate gradient loss respect to Z1 (output_gradients)
dL_dZ1 = tape.gradient(loss, Z1)  # Shape: (4, 5)

# Calculate gradient Z1 respect to W1 and b1, dL_dZ1 as output_gradients
grads_Z1 = tape.gradient(Z1, [W1, b1], output_gradients=dL_dZ1)

# Calculate gradient loss directly
grads_loss = tape.gradient(loss, [W1, b1])

print("Shape of Z1:", Z1.shape)
print("Shape if dL/dZ1 (output_gradients):", dL_dZ1.shape)
print("Gradient of W1 respect to Z1:", grads_Z1[0].shape)
print("Gradient of b1 respect Z1:", grads_Z1[1].shape)
print("\nGradient of W1 from loss:", grads_loss[0].shape)
print("Gradient of b1 from loss:", grads_loss[1].shape)

print("\nGradient of W1 respect to Z1 (sample):", grads_Z1[0].numpy())
print("Gradient of b1 respect to Z1 (sample):", grads_Z1[1].numpy())

print("\nGradient of W1 respect to Z1 ():", grads_loss[0].numpy())
print("Gradient of b1 respect to Z1 ():", grads_loss[1].numpy())

del tape

Shape of Z1: (4, 5)
Shape if dL/dZ1 (output_gradients): (4, 5)
Gradient of W1 respect to Z1: (3, 5)
Gradient of b1 respect Z1: (5,)

Gradient of W1 from loss: (3, 5)
Gradient of b1 from loss: (5,)

Gradient of W1 respect to Z1 (sample): [[-0.2712224   5.192976   -4.9743233  -5.4032884  -2.54095   ]
 [-1.0304453   2.3195715  -2.850347   -1.0263993  -0.7717415 ]
 [-0.59393656 -2.7924957   2.1636293   2.139062    0.56858635]]
Gradient of b1 respect to Z1 (sample): [ 0.67276305  3.2839744  -2.5621939   4.9858756   2.0584655 ]

Gradient of W1 respect to Z1 (): [[-0.2712224   5.192976   -4.9743233  -5.4032884  -2.54095   ]
 [-1.0304453   2.3195715  -2.850347   -1.0263993  -0.7717415 ]
 [-0.59393656 -2.7924957   2.1636293   2.139062    0.56858635]]
Gradient of b1 respect to Z1 (): [ 0.67276305  3.2839744  -2.5621939   4.9858756   2.0584655 ]


In [10]:
import tensorflow as tf

# input data
X = tf.random.normal((4, 3), dtype=tf.float32)  # batch_size=4, input_dim=3
y_true = tf.random.normal((4, 2), dtype=tf.float32)  # output_dim=2
m = X.shape[0]

# init layer 1
W1 = tf.Variable(tf.random.normal((3, 5)), trainable=True)  # input_dim=3, hidden_dim1=5
b1 = tf.Variable(tf.zeros((5,)), trainable=True)

# init layer 2
W2 = tf.Variable(tf.random.normal((5, 4)), trainable=True)  # hidden_dim1=5, hidden_dim2=4
b2 = tf.Variable(tf.zeros((4,)), trainable=True)

# init layer 3
W3 = tf.Variable(tf.random.normal((4, 2)), trainable=True)  # hidden_dim2=4, output_dim=2
b3 = tf.Variable(tf.zeros((2,)), trainable=True)

# L2 regularization
l2_lambda = 0.01

# Optimizer
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

# Forward pass and loss
with tf.GradientTape(persistent=True) as tape:
    # layer 1
    Z1 = tf.matmul(X, W1) + b1  # Shape: (4, 5)
    A1 = tf.nn.relu(Z1)
    # layer 2
    Z2 = tf.matmul(A1, W2) + b2  # Shape: (4, 4)
    A2 = tf.nn.relu(Z2)
    # layer 3
    Z3 = tf.matmul(A2, W3) + b3  # Shape: (4, 2)
    # MSE
    mse_loss = tf.reduce_mean(tf.square(Z3 - y_true))
    # L2 regularization
    l2_loss = (l2_lambda / (2 * m)) * (tf.reduce_sum(tf.square(W1)) +
                           tf.reduce_sum(tf.square(W2)) +
                           tf.reduce_sum(tf.square(W3)))
    # loss
    loss = mse_loss + l2_loss

# Loss gradient respect to Z1 (output_gradients)
dL_dZ1 = tape.gradient(loss, Z1)  # Shape: (4, 5)

# Z1 gradient respect to W1 and b1, dL_dZ1 as output_gradients
grads_Z1 = tape.gradient(Z1, [W1, b1], output_gradients=dL_dZ1)

# gradient before update
print("Trước khi cập nhật:")
print("Gradient of W1 respect to Z1:", grads_Z1[0].shape)
print("Gradient of b1 respect to Z1:", grads_Z1[1].shape)
print("W1 (sample):", W1.numpy()[:1])  # In một phần của W1
print("b1 (sample):", b1.numpy())

# update W1 and b1 with optimizer
optimizer.apply_gradients(zip(grads_Z1, [W1, b1]))

# after update
print("\nafter update:")
print("W1 (sample):", W1.numpy()[:1])
print("b1 (sample):", b1.numpy())

# Calculate gradient directly from loss for comparison
grads_loss = tape.gradient(loss, [W1, b1])
print("\nGradient of W1 from loss:", grads_loss)

Trước khi cập nhật:
Gradient of W1 respect to Z1: (3, 5)
Gradient of b1 respect to Z1: (5,)
W1 (sample): [[ 0.43060923  1.0141916  -0.03314429 -0.8431729   0.16362168]]
b1 (sample): [0. 0. 0. 0. 0.]

after update:
W1 (sample): [[ 0.42060935  1.0241914  -0.04314412 -0.8431729   0.15362184]]
b1 (sample): [-0.00999985  0.00999971 -0.00999975  0.         -0.00999986]

Gradient of W1 from loss: [<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[ 0.6521372 , -0.24911337,  0.3128932 , -0.00210793,  0.37297145],
       [-0.2019589 ,  0.07567654, -0.10010789, -0.00231517,  0.15473682],
       [ 0.11489109, -0.04442035,  0.05580609, -0.00268249,  0.3435624 ]],
      dtype=float32)>, <tf.Tensor: shape=(5,), dtype=float32, numpy=
array([ 0.363914  , -0.14066054,  0.17493972,  0.        ,  0.4564374 ],
      dtype=float32)>]
